### ISSUE TITLE
crashing on this

### ISSUE THREAD

**Issue by 99paulomondi** [BEN00262/simple-js-html-templating#1]
<script>
        let render = RenderComponent(`
        <% for (let r = 0; r < data.length;r++){%>
            <div class="col-md-2" id="products">
                <a href="#">
                    <img src="<% data[r].imageURL %>" alt="" width="100%" class="pb-3 pt-2">
                    <p><% data[r].name %></p>
                    <p class="text-muted">KSh <% data[r].price%></p>
                </a>
                <button type="button" class="btn btn-warning" class="pb-2" data-toggle="modal" data-target="#dell">view</button>
            </div>
        <%}%>
        `,document.getElementById("root"));

        render([{
            imageURL:"assets/images/11.jpg",
            name:"Dell Latitude E7740",
            price:"38,999"
        }])
    </script> -->

**Comment by BEN00262** [comment]
solved
